name: "Doctor's Financial"
favicon: null
layout_spectrum: 0.5018
typography_spectrum: 0.74505
title: "Doctor's Financial"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#98B8C8'
    - '#0890D0'
    - '#508098'
    - '#0088C8'
    - '#A0F0F8'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.488487
purpose: []
