name: "Doctor's Financial"
favicon: null
layout_spectrum: 0.5018
typography_spectrum: 0.74505
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#007db8'
    - '#003153'
    - '#a0d2f8'
    - '#be936a'
  brandStrength: 1
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
