analytics: {}
color:
  brandColors:
    - '#98B8C8'
    - '#0890D0'
    - '#508098'
    - '#0088C8'
    - '#A0F0F8'
  brandStrength: 1
  lightness: 0.75
  rhythmicContrast: 0.488487
  saturation: 0
cta: {}
layout_spectrum: 0.5018
name: "Doctor's Financial"
opengraph: {}
purpose: []
typography_spectrum: 0.74505
